[package]
name = "pg-control"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
telegram = ["dep:teloxide"]

[dependencies]
serde.workspace = true
thiserror.workspace = true
teloxide = { version = "0.17", default-features = false, features = ["rustls"], optional = true }
