[package]
name = "pg-ibkr"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
sdk = ["dep:ibapi"]

[dependencies]
async-trait.workspace = true
pg-execution = { path = "../../crates/pg-execution" }
pg-marketdata = { path = "../../crates/pg-marketdata" }
pg-types = { path = "../../crates/pg-types" }
ibapi = { version = "3.3", optional = true }
