[package]
name = "pg-ibkr"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
sdk = ["dep:ibapi", "dep:futures", "dep:time"]

[dependencies]
async-trait.workspace = true
pg-execution = { path = "../../crates/pg-execution" }
pg-marketdata = { path = "../../crates/pg-marketdata" }
pg-types = { path = "../../crates/pg-types" }
rust_decimal.workspace = true
tokio.workspace = true
futures = { version = "0.3", optional = true }
time = { version = "0.3", optional = true }
ibapi = { version = "4.0.1", default-features = false, features = ["async"], optional = true }
