[package]
name = "pg-store"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
pg-oms = { path = "../pg-oms" }
pg-reconcile = { path = "../pg-reconcile" }
pg-types = { path = "../pg-types" }
serde_json.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tokio.workspace = true
uuid.workspace = true
