[package]
name = "pg-strategy"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
pg-marketdata = { path = "../pg-marketdata" }
pg-types = { path = "../pg-types" }
rust_decimal.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
